# Generated by Django 4.2.7 on 2023-11-16 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webControl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mode',
            name='mode',
        ),
    ]
